"""
PDF Generator for BIS Saathi Certification Roadmap.
Uses ReportLab to generate a clean, professional 1-page compliance roadmap snapshot.
Scoped to standard statutory English to avoid Indic font shaping issues.
Clearly demarcated as an unofficial hackathon prototype with statutory disclaimers.
"""

import io
from datetime import datetime
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_roadmap_pdf(journey_data: Dict[str, Any]) -> bytes:
    """
    Generates a 1-page PDF byte stream representing the certification roadmap.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=32,
        bottomMargin=32
    )

    styles = getSampleStyleSheet()
    
    # Custom Palette
    navy = colors.HexColor("#0f172a")
    saffron = colors.HexColor("#ea580c")
    slate = colors.HexColor("#475569")
    light_bg = colors.HexColor("#f8fafc")
    border_color = colors.HexColor("#cbd5e1")
    emerald = colors.HexColor("#16a34a")
    amber = colors.HexColor("#d97706")

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=18,
        textColor=navy
    )

    badge_style = ParagraphStyle(
        "DocBadge",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=10,
        textColor=saffron
    )

    disclaimer_style = ParagraphStyle(
        "DocDisclaimer",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=7,
        leading=9,
        textColor=slate
    )

    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=12,
        textColor=navy
    )

    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10.5,
        textColor=navy
    )

    body_bold = ParagraphStyle(
        "DocBodyBold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10.5,
        textColor=navy
    )

    table_header = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=9.5,
        textColor=colors.white
    )

    step_title_style = ParagraphStyle(
        "StepTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=9.5,
        textColor=navy
    )

    step_desc_style = ParagraphStyle(
        "StepDesc",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=7,
        leading=8.5,
        textColor=slate
    )

    story = []

    # 1. Header & Prototyping Disclaimer
    metadata = journey_data.get("metadata", {})
    standard_id = journey_data.get("standard_id", "BIS Standard")
    readiness_score = journey_data.get("readiness_score", 0)
    steps = journey_data.get("steps", [])
    journey_id = journey_data.get("journey_id", "N/A")[:8]
    now_str = datetime.now().strftime("%d %b %Y, %H:%M IST")

    story.append(Paragraph("BIS Saathi — Compliance & Certification Roadmap", title_style))
    story.append(Paragraph("UNOFFICIAL PREPAREDNESS CHECKLIST • SMART INDIA HACKATHON PROTOTYPE (SIH26107)", badge_style))
    story.append(Spacer(1, 4))

    # Disclaimer Box
    disclaimer_text = (
        "<b>DISCLAIMER:</b> This roadmap is an automated preparedness tool generated by the BIS Saathi prototype for "
        "planning and internal factory guidance. It does <b>NOT</b> constitute an official BIS certificate, licence, or statutory document. "
        "Official licensing procedures, mandatory QCO enforcement, and fee schedules must be verified directly at "
        "<b>www.manakonline.in</b> or <b>www.bis.gov.in</b>."
    )
    disclaimer_table = Table(
        [[Paragraph(disclaimer_text, disclaimer_style)]],
        colWidths=[540]
    )
    disclaimer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#fffbeb")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#fef3c7")),
        ('PADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(disclaimer_table)
    story.append(Spacer(1, 6))

    # 2. Key Target Metadata Table
    title_text = metadata.get("title", "Standard Title")
    qco_status = metadata.get("qco_status", "Mandatory")
    scheme_name = metadata.get("scheme_name", journey_data.get("scheme", "Scheme-I"))
    governing_law = metadata.get("governing_law", "BIS Act, 2016")

    meta_content = [
        [
            Paragraph("<b>Target Standard:</b>", body_bold),
            Paragraph(f"<b>{standard_id}</b> — {title_text}", body_style),
            Paragraph("<b>QCO Enforcement:</b>", body_bold),
            Paragraph(f"<font color='{'#b91c1c' if 'mandat' in qco_status.lower() else '#15803d'}'><b>{qco_status.upper()}</b></font>", body_style)
        ],
        [
            Paragraph("<b>Conformity Scheme:</b>", body_bold),
            Paragraph(scheme_name, body_style),
            Paragraph("<b>Governing Statute:</b>", body_bold),
            Paragraph(governing_law, body_style)
        ]
    ]

    meta_table = Table(meta_content, colWidths=[100, 200, 100, 140])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), light_bg),
        ('BOX', (0, 0), (-1, -1), 0.5, border_color),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, border_color),
        ('PADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 6))

    # 3. Readiness Score Bar
    score_color = emerald if readiness_score >= 80 else (amber if readiness_score >= 40 else saffron)
    score_html = (
        f"<b>Preparedness Readiness Score:</b> &nbsp; "
        f"<font color='{score_color.hexval()}'><b>{readiness_score}% Completed</b></font> &nbsp; "
        f"({sum(1 for s in steps if s.get('status') == 'done')} of {len(steps)} steps achieved)"
    )
    score_table = Table([[Paragraph(score_html, body_bold)]], colWidths=[540])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
        ('BOX', (0, 0), (-1, -1), 0.5, border_color),
        ('PADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 6))

    # 4. Step-by-Step Checklist
    story.append(Paragraph("Certification Milestone Checklist (Free-Form Workflow)", section_heading))
    story.append(Spacer(1, 3))

    step_rows = [
        [
            Paragraph("Status", table_header),
            Paragraph("#", table_header),
            Paragraph("Action & Compliance Milestone", table_header),
            Paragraph("Est. Timeline", table_header)
        ]
    ]

    for s in steps:
        is_done = s.get("status") == "done"
        status_symbol = "[✓] DONE" if is_done else "[  ] PENDING"
        status_color = "#15803d" if is_done else "#64748b"

        status_p = Paragraph(f"<font color='{status_color}'><b>{status_symbol}</b></font>", body_bold)
        num_p = Paragraph(str(s.get("step_number", "-")), body_style)

        title_p = Paragraph(s.get("title", ""), step_title_style)
        desc_p = Paragraph(s.get("description", ""), step_desc_style)
        milestone_cell = [title_p, desc_p]

        timeline_p = Paragraph(s.get("indicative_timeline", "N/A"), step_desc_style)

        step_rows.append([status_p, num_p, milestone_cell, timeline_p])

    checklist_table = Table(step_rows, colWidths=[70, 20, 360, 90])
    checklist_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), navy),
        ('ALIGN', (0, 0), (1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.3, border_color),
        ('PADDING', (0, 0), (-1, -1), 3),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, light_bg])
    ]))
    story.append(checklist_table)
    story.append(Spacer(1, 6))

    # 5. Recognized Testing Laboratories (If available)
    labs = metadata.get("labs", [])
    if labs:
        story.append(Paragraph("Accredited Testing Facilities (Sample Mapping)", section_heading))
        story.append(Spacer(1, 2))

        lab_items = []
        for l in labs:
            lab_items.append(Paragraph(f"• <b>{l.get('name')}</b> ({l.get('city')}) — Phone/Contact: {l.get('phone')}", step_desc_style))

        labs_table = Table([[item] for item in lab_items], colWidths=[540])
        labs_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), light_bg),
            ('BOX', (0, 0), (-1, -1), 0.5, border_color),
            ('PADDING', (0, 0), (-1, -1), 3),
        ]))
        story.append(labs_table)
        story.append(Spacer(1, 6))

    # 6. Footer Audit Note
    footer_text = (
        f"Roadmap ID: {journey_id} | Generated: {now_str} | Official e-BIS Portal: https://www.manakonline.in | "
        "Standard statutory English edition."
    )
    story.append(Paragraph(footer_text, disclaimer_style))

    # Build document
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
